build:
  environment:
    php:
      version: 8.3
    node: "v19.4.0"
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [ php-scrutinizer-run ]
    coverage:
      tests:
        before:
          - command: git config --global user.email "github-actions@example.com" && git config --global user.name "GitHub Actions"
        override:
          - command: XDEBUG_MODE=coverage ./vendor/bin/pest --coverage --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover

filter:
  excluded_paths: [ tests/* ]

checks:
  php:
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true
